### ISSUE TITLE
separating dependencies into requirements*.txt?

### ISSUE THREAD

**Issue by gliptak** [pypa/sampleproject#130]
An example is at:

https://github.com/pydata/pandas-datareader/blob/master/setup.py#L17

Please let me know if you are open to a PR updating ```setup.py``` as above.

**Comment by dmtucker** [comment]
I would not advocate for that. What is the motivation for it?

**Comment by gliptak** [comment]
Motivation is that a developer or developer tooling can run ```pip installl``` using ``requirements*.txt``` files and ```setup.py``` stays in sync. You see many projects listing out-of-sync dependencies between their requirements and setup.py

**Comment by dmtucker** [comment]
That does not seem like a typical usage of `requirements.txt` (related: https://caremad.io/posts/2013/07/setup-vs-requirement/).
`pip install .` (or `tox --devenv`) will install anything in `install_requires` without the need for a `requirements.txt`.
Why do you need both?

**Comment by di** [comment]
Hi @gliptak, thanks for the suggestion. I would also argue that this is an anti-pattern, and that we won't plan to support something similar here. I'd recommend reading https://caremad.io/posts/2013/07/setup-vs-requirement/.

**Comment by gliptak** [comment]
Thank you for the great link.

So maybe above style ```requirements.txt``` is to be added to the project?

Also are ```pip install``` flags targeting load of requirement-dev and requrements-test dependencies directly from ```setup.py```?

**Comment by dmtucker** [comment]
IMO, `tox` runs the show for dev and test, so those dependencies should go in [a `deps` section](https://github.com/pydata/pandas-datareader/blob/adb67b2e959f2060a9db18f8b343d06e917f23da/tox.ini#L7). You can get a virtualenv with those `deps` by running `tox --devenv`, optionally with `-e` if you have multiple environments (e.g. [one for static analysis](https://github.com/dmtucker/backlog/blob/ccc3618337d529e94c749889172675a7d1240168/tox.ini#L40)). I do not use `setup.py test` (or any other `setuptools` command directly).

**Comment by relaxdiego** [comment]
Sharing my own experience.

I also use tox's `deps` section but it references a `requirements-dev.txt` file. The reason for the separation is that while I use `tox` as a final step just before committing and pushing a change, I use pytest via `test.vim` to do very quick and selective execution of tests while I'm coding ([relevant part of my dotfiles](https://github.com/relaxdiego/dotfiles/blob/555114aac10cbe55a92be30e001b7326b2940d84/dot_vimrc#L235-L242)) because tox is just too slow for me.

In order for me to do the above while avoiding duplicated dependency declarations everywhere, I keep the dev devepencies in that `requirements-dev.txt` file while the runtime dependencies stay in setup.py. Here's one of my pet projects that exemplifies the structure: https://github.com/relaxdiego/aircraft

**Comment by gliptak** [comment]
Maybe workflow best practice highlights could be added to README

**Comment by dmtucker** [comment]
@relaxdiego Do you manually create a virtualenv or does `test.vim` do that for you?

**Comment by relaxdiego** [comment]
@dmtucker I manually create it. Starting in [this part of the readme](https://github.com/relaxdiego/aircraft#prepare-your-python-environment-pyenv-style-one-time-only), one can either use pyenv (my preference) or the more widely accepted (I think) venv style.

**Comment by dmtucker** [comment]
Gotcha... Seems like `tox --devenv` in multiple steps :thinking:

**Comment by relaxdiego** [comment]
@dmtucker it is, yes. My motivation for doing it that way though is because when I code, I have vim do split windows where the left window is my test file and my right window is my code. I will jump between windows frequently and I test often. Using tox for this produces a lag that adds up over time whereas pytest does not. That's why I avoid using tox up until the very last step just before I commit my changes.

**Comment by dmtucker** [comment]
Would you not just call `tox --devenv` once, then use `pytest` the same way you currently do?
``` sh
tox --devenv ./venv
venv/bin/pytest ...
venv/bin/pytest ...
source venv/bin/activate
pytest ...
pytest ...
```

**Comment by relaxdiego** [comment]
sure that works too, especially for those that like the venv style. i'm partial to pyenv though since i always forget to run that `source ...` part. :-)
