### ISSUE TITLE
The package name

### ISSUE THREAD

**Issue by 4e1e0603** [pypa/sampleproject#198]
The package directory is named *sample*, but the package itself is named *sampleproject*. Is it by intention? While possible, it is a little bit confusing, especially for beginners.

```shell
src/
  sample/
```

vs 

```shell
name = "sampleproject"
```

**Comment by pfmoore** [comment]
IMO it emphasises that the import name and the package name are different things. While using the same name is often the right thing to do, I think we should make the distinction clear, *especially* for beginners who may otherwise be confused about why they have to specify "the same thing" twice.

Having different names here is a simple and effective way of making that point.

**Comment by groundf** [comment]
Thank you for your kind explanation.

**Comment by jeanas** [comment]
Closing as resolved.
