### ISSUE TITLE
Update tox version? And tox best practices?

### ISSUE THREAD

**Issue by VladimirFokow** [pypa/sampleproject#208]
The `tox` [docs](https://tox.wiki/en/latest/user_guide.html) use `>=4`

It is safe to update it here? Currently:
```.ini
# Define the minimal tox version required to run;
# if the host tox is less than this the tool with create an environment and
# provision it with a tox that satisfies it under provision_tox_env.
# At least this version is needed for PEP 517/518 support.
minversion = 3.3.0
```

\+ I know this repo isn't intended to show `tox` best practices, but if they've changed (I don't know), they can also be changed here. (E.g., move the `tox` configuration [to `pyproject.toml`](https://tox.wiki/en/latest/config.html#pyproject-toml)?) -  I haven't used `tox` so I don't know

**Comment by pfmoore** [comment]
FWIW, when I originally created this repository, "testing best practices" was explicitly excluded, because there was no consensus. While things have improved, I still don't think there's sufficient consensus that we should be worrying about tox best practices (I personally use and prefer nox).

IMO the tests here should be *examples* and we shouldn't even be running CI.

For expediency, I'd say:

1. Use whatever tox setup works to get CI to run.
2. Definitely don't put tox config in `pyproject.toml`, because that makes it harder for users to determine what's part of the "recommended config" and what's specific to this project's infrastructure.

But for better maintainability, if anyone wants to do the work, I'd support switching to nox, which doesn't need any config outside of a `noxfile.py` and which supports Python 3.7+.

**Comment by chrysle** [comment]
> But for better maintainability, if anyone wants to do the work, I'd support switching to nox, which doesn't need any config outside of a `noxfile.py` and which supports Python 3.7+.

I'd be willing to introduce that!
